### ISSUE TITLE
Optionally add additional software sources

### ISSUE THREAD

**Issue by foretspaisibles** [melusina-org/gha-testsuite#3]
```
sources:
  - rsync: server
  - git: git@…
  - zip: URL
  - tar: URL
```

Describe different methods, most produce a file: source in the sources file. Part of the cache key.
